### ISSUE TITLE
送信失敗時の再接続処理を追加

### ISSUE THREAD

**Issue by kadoshita** [kadoshita/serial2influxdb#1]

**Comment by kadoshita** [comment]
エラー

```
ERROR: Retry buffer closed with 1 items that were not written to InfluxDB!
f [Error]: 503 Service Unavailable : upstream connect error or disconnect/reset before headers. reset reason: connection failure
    at IncomingMessage.<anonymous> (/home/sublimer/workspace/serial2influxdb/node_modules/@influxdata/influxdb-client/dist/index.js:16:7570)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  statusCode: 503,
  statusMessage: 'Service Unavailable',
  body: 'upstream connect error or disconnect/reset before headers. reset reason: connection failure',
  message: '503 Service Unavailable : upstream connect error or disconnect/reset before headers. reset reason: connection failure',
  _retryAfter: 0
}
WARN: Write to influx DB failed (remaining attempts: 2). g [Error]: Request timed out
    at ClientRequest.<anonymous> (/home/sublimer/workspace/serial2influxdb/node_modules/@influxdata/influxdb-client/dist/index.js:16:7794)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
    at Object.onceWrapper (events.js:416:28)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  message: 'Request timed out'
}
ERROR: Retry buffer closed with 1 items that were not written to InfluxDB!
g [Error]: Request timed out
    at ClientRequest.<anonymous> (/home/sublimer/workspace/serial2influxdb/node_modules/@influxdata/influxdb-client/dist/index.js:16:7794)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
    at Object.onceWrapper (events.js:416:28)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  message: 'Request timed out'
}
```
